/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzariagui;

import interfaces.IComponente;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import pizzaDecorator.PizzaDecorator;
import pizzaSimples.PizzaSimples;

/**
 *
 * @author Renata
 */
public class TelaAvancada extends javax.swing.JFrame {

    /**
     * Creates new form TelaAvancada
     */
    public TelaAvancada() {
        initComponents();
        carregarListaIngredientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ingredientes = new ArrayList<String>();
        escolhas = new ArrayList<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOpcoes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOpcoesEscolhidas = new javax.swing.JList<>();
        btnEscolha = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConcluirPedido = new javax.swing.JButton();
        btnMoverPraCima = new javax.swing.JButton();
        btnMoverPraBaixo = new javax.swing.JButton();

        ingredientes = org.jdesktop.observablecollections.ObservableCollections.observableList(ingredientes);

        escolhas = org.jdesktop.observablecollections.ObservableCollections.observableList(escolhas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha os ingredientes");

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ingredientes, jListOpcoes);
        bindingGroup.addBinding(jListBinding);

        jScrollPane1.setViewportView(jListOpcoes);

        jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, escolhas, jListOpcoesEscolhidas);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(jListOpcoesEscolhidas);

        btnEscolha.setText(">");
        btnEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolhaActionPerformed(evt);
            }
        });

        btnVoltar.setText("<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConcluirPedido.setText("Concluir Pedido");
        btnConcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirPedidoActionPerformed(evt);
            }
        });

        btnMoverPraCima.setText("Para cima");
        btnMoverPraCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverPraCimaActionPerformed(evt);
            }
        });

        btnMoverPraBaixo.setText("Para baixo");
        btnMoverPraBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverPraBaixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEscolha)
                                    .addComponent(btnVoltar))
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMoverPraCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMoverPraBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnConcluirPedido)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnEscolha)
                        .addGap(30, 30, 30)
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnMoverPraCima)
                        .addGap(31, 31, 31)
                        .addComponent(btnMoverPraBaixo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnConcluirPedido)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolhaActionPerformed
         String mudanca = jListOpcoes.getSelectedValue();
         escolhas.add(mudanca);
         
         
    }//GEN-LAST:event_btnEscolhaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
         int indice = jListOpcoesEscolhidas.getSelectedIndex();
         escolhas.remove(indice);
         
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnMoverPraCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverPraCimaActionPerformed
        String elementoSustituido; 
        String elementoSustituidor; 
        int indice = jListOpcoesEscolhidas.getSelectedIndex();
        if(indice != 0) {
           elementoSustituidor = (String) escolhas.get(indice);
           elementoSustituido = (String) escolhas.get(indice-1);
           escolhas.set(indice-1,elementoSustituidor);
           escolhas.set(indice,elementoSustituido);
         }
            
    }//GEN-LAST:event_btnMoverPraCimaActionPerformed

    private void btnMoverPraBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverPraBaixoActionPerformed
        String elementoSustituido; 
        String elementoSustituidor; 
        int indice = jListOpcoesEscolhidas.getSelectedIndex();
        if(indice < escolhas.size()-1) {
           elementoSustituidor = (String) escolhas.get(indice);
           elementoSustituido = (String) escolhas.get(indice+1);
           escolhas.set(indice+1,elementoSustituidor);
           escolhas.set(indice,elementoSustituido);
        }
    }//GEN-LAST:event_btnMoverPraBaixoActionPerformed

    private void btnConcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirPedidoActionPerformed
        ArrayList<PizzaDecorator> ingredientesDecorator = new ArrayList<>();
        PizzaDecorator auxDecorator;
        PizzaSimples auxSimples;
        File currentDir = new File("./plugins");
        String []plugins = currentDir.list();
        int i;
        URL[] jars = new URL[plugins.length];
        for(i = 0; i < plugins.length; i++) {
            try {
                jars[i] = (new File("./plugins/" + plugins[i])).toURL();
            } catch (MalformedURLException ex) {
                Logger.getLogger(TelaAvancada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        URLClassLoader ulc = new URLClassLoader(jars);
        
        String pedido;
        for(i = 0; i < escolhas.size(); i++) {
            pedido = (String) escolhas.get(i);
            try {
                ingredientesDecorator.add((PizzaDecorator) Class.forName(pedido.toLowerCase() + "." + pedido, true, ulc).newInstance());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaAvancada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(TelaAvancada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(TelaAvancada.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        for(i = 0; i < ingredientesDecorator.size()-1; i++){
            auxDecorator = (PizzaDecorator) ingredientesDecorator.get(i);
            auxDecorator.setDecorator((PizzaDecorator)ingredientesDecorator.get(i+1));
        }
        auxSimples = new PizzaSimples();
        if(!ingredientesDecorator.isEmpty()){
           auxDecorator = (PizzaDecorator) ingredientesDecorator.get(i);
           auxDecorator.setDecorator(auxSimples);
           System.out.println(((PizzaDecorator) ingredientesDecorator.get(0)).adicionar());
        }
        else
            System.out.println(auxSimples.adicionar());
        
    }//GEN-LAST:event_btnConcluirPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvancada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluirPedido;
    private javax.swing.JButton btnEscolha;
    private javax.swing.JButton btnMoverPraBaixo;
    private javax.swing.JButton btnMoverPraCima;
    private javax.swing.JButton btnVoltar;
    private java.util.List escolhas;
    private java.util.List ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListOpcoes;
    private javax.swing.JList<String> jListOpcoesEscolhidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    public void carregarListaIngredientes(){
        
         File currentDir = new File("./plugins");
         String []plugins = currentDir.list();
         int i;
         String nome;
         for (i = 0; i < plugins.length; i++){
              nome = plugins[i].split("\\.")[0];
	      ingredientes.add(nome);
   
         }
        
    }
    

}
